# Generated by Django 4.1.5 on 2023-01-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
